load(":defs.bzl", "python_tool")

python_tool(
    name = "acquire_git",
    src = "acquire_git.py",
    visibility = ["PUBLIC"],
)

python_tool(
    name = "acquire_http",
    src = "acquire_http.py",
    visibility = ["PUBLIC"],
)

python_tool(
    name = "acquire_embedded",
    src = "acquire_embedded.py",
    visibility = ["PUBLIC"],
)

python_tool(
    name = "acquire_cargo",
    src = "acquire_cargo.py",
    visibility = ["PUBLIC"],
)

python_tool(
    name = "acquire_oci",
    src = "acquire_oci.py",
    visibility = ["PUBLIC"],
)

python_tool(
    name = "acquire_project_source",
    src = "acquire_project_source.py",
    visibility = ["PUBLIC"],
)

python_tool(
    name = "merge_source_manifest",
    src = "merge_source_manifest.py",
    visibility = ["PUBLIC"],
)

python_tool(
    name = "build_element",
    src = "build_element.py",
    srcs = ["root//:bst2nix_sources"],
    visibility = ["PUBLIC"],
)
