from __future__ import annotations

import json
import hashlib
import re
from typing import Any

from .source_lock import SourceLockError


def _quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def generate_buck_sources(lock: dict[str, Any]) -> str:
    sources = lock.get("sources")
    if not isinstance(sources, dict):
        raise SourceLockError("source lock has no sources mapping")
    lines = [
        "# Generated by bst2nix; do not edit.",
        'load("@root//buck2:git_acquire.bzl", "git_repo_acquire")',
        'load("@root//buck2:http_acquire.bzl", "http_acquire")',
        'load("@root//buck2:embedded_acquire.bzl", "embedded_acquire")',
        'load("@root//buck2:cargo_acquire.bzl", "cargo_acquire")',
        'load("@root//buck2:oci_acquire.bzl", "oci_acquire")',
        'load("@root//buck2:project_source.bzl", "project_source")',
        'load("@root//buck2:source_manifest.bzl", "source_manifest")',
        "",
    ]
    groups: dict[tuple[str, bool], list[tuple[str, str]]] = {}
    count = 0
    for source_id, source in sorted(sources.items()):
        if not re.fullmatch(r"[0-9a-f]{64}", source_id):
            raise SourceLockError(f"invalid source ID: {source_id!r}")
        if not isinstance(source, dict) or source.get("fetcher") != "git":
            continue
        revision, url = source.get("revision"), source.get("url")
        if not isinstance(revision, str) or not isinstance(url, str):
            raise SourceLockError(f"malformed Git source: {source_id}")
        groups.setdefault((url, bool(source.get("submodules"))), []).append(
            (source_id, revision)
        )
        count += 1
    group_names = []
    for (url, submodules), members in sorted(groups.items()):
        group_id = hashlib.sha256(
            json.dumps([url, submodules], separators=(",", ":")).encode()
        ).hexdigest()
        group_name = f"git-repo-{group_id}"
        group_names.append(group_name)
        lines.extend(
            [
                "git_repo_acquire(",
                f'    name = "{group_name}",',
                "    sources = {",
                *[
                    f"        {_quote(source_id)}: {_quote(revision)},"
                    for source_id, revision in members
                ],
                "    },",
                '    tool = "root//tools:acquire_git",',
                f"    url = {_quote(url)},",
                f"    submodules = {'True' if submodules else 'False'},",
                '    visibility = ["PUBLIC"],',
                ")",
                "",
            ]
        )
    http_ids = []
    for source_id, source in sorted(sources.items()):
        if not isinstance(source, dict) or source.get("fetcher") not in {
            "tar", "zip", "remote", "archive"
        }:
            continue
        lines.extend([
            "http_acquire(",
            f'    name = "http-{source_id}",',
            f"    url = {_quote(source['url'])},",
            f"    sha256 = {_quote(source['sha256'])},",
            f"    kind = {_quote(source['fetcher'])},",
            *(
                [f"    filename = {_quote(source['filename'])},"]
                if source.get("filename")
                else []
            ),
            '    tool = "root//tools:acquire_http",',
            '    visibility = ["PUBLIC"],',
            ")",
            "",
        ])
        http_ids.append(source_id)
    project_ids = []
    projects = lock.get("projects", {})
    for source_id, source in sorted(sources.items()):
        if not isinstance(source, dict) or source.get("fetcher") not in {
            "local", "patch", "patch_queue"
        }:
            continue
        project = projects.get(source.get("project"), {})
        if not project.get("url") or not project.get("revision"):
            raise SourceLockError(
                f"project source {source_id} has no locked project repository"
            )
        lines.extend([
            "project_source(",
            f'    name = "project-{source_id}",',
            f"    url = {_quote(project['url'])},",
            f"    revision = {_quote(project['revision'])},",
            f"    path = {_quote(source['path'])},",
            '    tool = "root//tools:acquire_project_source",',
            '    visibility = ["PUBLIC"],',
            ")",
            "",
        ])
        project_ids.append(source_id)
    embedded_ids = []
    for source_id, source in sorted(sources.items()):
        if not isinstance(source, dict) or source.get("fetcher") != "embedded":
            continue
        lines.extend([
            "embedded_acquire(",
            f'    name = "embedded-{source_id}",',
            f"    encoding = {_quote(source['encoding'])},",
            f"    data = {_quote(source['data'])},",
            f"    filename = {_quote(source['filename'])},",
            '    tool = "root//tools:acquire_embedded",',
            '    visibility = ["PUBLIC"],',
            ")",
            "",
        ])
        embedded_ids.append(source_id)
    cargo_ids = []
    for source_id, source in sorted(sources.items()):
        if not isinstance(source, dict) or source.get("fetcher") != "cargo":
            continue
        lines.extend([
            "cargo_acquire(",
            f'    name = "cargo-{source_id}",',
            f"    spec = {_quote(source)},",
            '    tool = "root//tools:acquire_cargo",',
            '    visibility = ["PUBLIC"],',
            ")",
            "",
        ])
        cargo_ids.append(source_id)
    oci_ids = []
    for source_id, source in sorted(sources.items()):
        if not isinstance(source, dict) or source.get("fetcher") != "oci":
            continue
        lines.extend([
            "oci_acquire(",
            f'    name = "oci-{source_id}",',
            f"    url = {_quote(source['url'])},",
            f"    digest = {_quote(source['digest'])},",
            f"    architecture = {_quote(source['architecture'])},",
            '    tool = "root//tools:acquire_oci",',
            '    visibility = ["PUBLIC"],',
            ")",
            "",
        ])
        oci_ids.append(source_id)
    lines.extend(
        [
            "source_manifest(",
            '    name = "manifest",',
            "    groups = [",
            *[f'        ":{name}",' for name in group_names],
            "    ],",
            "    sources = {",
            *[
                f'        "{source_id}": ":http-{source_id}",'
                for source_id in http_ids
            ],
            *[
                f'        "{source_id}": ":project-{source_id}",'
                for source_id in project_ids
            ],
            *[
                f'        "{source_id}": ":embedded-{source_id}",'
                for source_id in embedded_ids
            ],
            *[
                f'        "{source_id}": ":cargo-{source_id}",'
                for source_id in cargo_ids
            ],
            *[
                f'        "{source_id}": ":oci-{source_id}",'
                for source_id in oci_ids
            ],
            "    },",
            '    tool = "root//tools:merge_source_manifest",',
            '    visibility = ["PUBLIC"],',
            ")",
            "",
        ]
    )
    lines.insert(1, f"# Git sources: {count}; repository actions: {len(groups)}")
    return "\n".join(lines)
