from __future__ import annotations

import json
import re
from typing import Any

from .source_lock import SourceLockError


def _quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def generate_buck_sources(lock: dict[str, Any]) -> str:
    sources = lock.get("sources")
    if not isinstance(sources, dict):
        raise SourceLockError("source lock has no sources mapping")
    lines = [
        "# Generated by bst2nix; do not edit.",
        'load("//buck2:git_acquire.bzl", "git_acquire")',
        'load("//buck2:source_manifest.bzl", "source_manifest")',
        "",
    ]
    git_ids = []
    count = 0
    for source_id, source in sorted(sources.items()):
        if not re.fullmatch(r"[0-9a-f]{64}", source_id):
            raise SourceLockError(f"invalid source ID: {source_id!r}")
        if not isinstance(source, dict) or source.get("fetcher") != "git":
            continue
        revision, url = source.get("revision"), source.get("url")
        if not isinstance(revision, str) or not isinstance(url, str):
            raise SourceLockError(f"malformed Git source: {source_id}")
        lines.extend(
            [
                "git_acquire(",
                f'    name = "git-{source_id}",',
                f"    revision = {_quote(revision)},",
                '    tool = "//tools:acquire_git",',
                f"    url = {_quote(url)},",
                f"    submodules = {'True' if source.get('submodules') else 'False'},",
                '    visibility = ["PUBLIC"],',
                ")",
                "",
            ]
        )
        git_ids.append(source_id)
        count += 1
    lines.extend(
        [
            "source_manifest(",
            '    name = "manifest",',
            "    sources = {",
            *[
                f'        "{source_id}": ":git-{source_id}",'
                for source_id in git_ids
            ],
            "    },",
            '    tool = "//tools:merge_source_manifest",',
            '    visibility = ["PUBLIC"],',
            ")",
            "",
        ]
    )
    lines.insert(1, f"# Git targets: {count}")
    return "\n".join(lines)
