from __future__ import annotations

import json
import hashlib
import re
from typing import Any

from .source_lock import SourceLockError


def _quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def generate_buck_sources(lock: dict[str, Any]) -> str:
    sources = lock.get("sources")
    if not isinstance(sources, dict):
        raise SourceLockError("source lock has no sources mapping")
    lines = [
        "# Generated by bst2nix; do not edit.",
        'load("@root//buck2:git_acquire.bzl", "git_repo_acquire")',
        'load("@root//buck2:source_manifest.bzl", "source_manifest")',
        "",
    ]
    groups: dict[tuple[str, bool], list[tuple[str, str]]] = {}
    count = 0
    for source_id, source in sorted(sources.items()):
        if not re.fullmatch(r"[0-9a-f]{64}", source_id):
            raise SourceLockError(f"invalid source ID: {source_id!r}")
        if not isinstance(source, dict) or source.get("fetcher") != "git":
            continue
        revision, url = source.get("revision"), source.get("url")
        if not isinstance(revision, str) or not isinstance(url, str):
            raise SourceLockError(f"malformed Git source: {source_id}")
        groups.setdefault((url, bool(source.get("submodules"))), []).append(
            (source_id, revision)
        )
        count += 1
    group_names = []
    for (url, submodules), members in sorted(groups.items()):
        group_id = hashlib.sha256(
            json.dumps([url, submodules], separators=(",", ":")).encode()
        ).hexdigest()
        group_name = f"git-repo-{group_id}"
        group_names.append(group_name)
        lines.extend(
            [
                "git_repo_acquire(",
                f'    name = "{group_name}",',
                "    sources = {",
                *[
                    f"        {_quote(source_id)}: {_quote(revision)},"
                    for source_id, revision in members
                ],
                "    },",
                '    tool = "root//tools:acquire_git",',
                f"    url = {_quote(url)},",
                f"    submodules = {'True' if submodules else 'False'},",
                '    visibility = ["PUBLIC"],',
                ")",
                "",
            ]
        )
    lines.extend(
        [
            "source_manifest(",
            '    name = "manifest",',
            "    groups = [",
            *[f'        ":{name}",' for name in group_names],
            "    ],",
            '    tool = "root//tools:merge_source_manifest",',
            '    visibility = ["PUBLIC"],',
            ")",
            "",
        ]
    )
    lines.insert(1, f"# Git sources: {count}; repository actions: {len(groups)}")
    return "\n".join(lines)
