from __future__ import annotations

import hashlib
import json
from typing import Any

from .build_plan import BuildPlanError, element_build_plan


def _quote(value: Any) -> str:
    return json.dumps(value, sort_keys=True)


def _target(name: str) -> str:
    return "element-" + hashlib.sha256(name.encode()).hexdigest()


def _source_group(source: dict[str, Any]) -> str:
    identity = json.dumps(
        [source["url"], bool(source.get("submodules"))], separators=(",", ":")
    )
    return "git-repo-" + hashlib.sha256(identity.encode()).hexdigest()


def _source_target(source_id: str, source: dict[str, Any]) -> str:
    if source["fetcher"] == "git":
        return _source_group(source)
    return "http-" + source_id


def generate_buck_elements(
    graph: dict[str, Any], source_lock: dict[str, Any]
) -> str:
    elements = graph.get("elements", {})
    declarations = source_lock.get("elements", {})
    sources = source_lock.get("sources", {})
    ready: set[str] = set()
    plans = {}
    pending = set(elements)
    while pending:
        progressed = False
        for name in sorted(pending):
            source_ids = declarations.get(name, [])
            if any(
                sources.get(source_id, {}).get("fetcher")
                not in {"git", "tar", "zip", "remote", "archive"}
                for source_id in source_ids
            ):
                continue
            dependencies = {
                dependency
                for values in elements[name].get("dependencies", {}).values()
                for dependency in values
            }
            if not dependencies <= ready:
                continue
            try:
                plans[name] = element_build_plan(graph, name)
            except BuildPlanError:
                continue
            ready.add(name)
            pending.remove(name)
            progressed = True
            break
        if not progressed:
            break

    lines = [
        "# Generated by bst2nix; do not edit.",
        f"# Executable elements: {len(ready)}; blocked elements: {len(elements) - len(ready)}",
        'load("@root//buck2:element_execute.bzl", "element_execute")',
        "",
    ]
    for name in sorted(ready):
        source_ids = declarations.get(name, [])
        dependency_names = sorted({
            dependency
            for values in elements[name].get("dependencies", {}).values()
            for dependency in values
        })
        lines.extend([
            "element_execute(",
            f"    name = {_quote(_target(name))},",
            "    spec = " + _quote({
                "plan": plans[name],
                "sources": {source_id: sources[source_id] for source_id in source_ids},
            }) + ",",
            "    sources = {",
            *[
                f"        {_quote(source_id)}: "
                f"\"generated_sources//:{_source_target(source_id, sources[source_id])}\","
                for source_id in source_ids
            ],
            "    },",
            "    dependencies = {",
            *[
                f"        {_quote(dependency)}: \":{_target(dependency)}\","
                for dependency in dependency_names
            ],
            "    },",
            '    tool = "root//tools:build_element",',
            '    visibility = ["PUBLIC"],',
            ")",
            "",
        ])
    if graph.get("target") in ready:
        lines.extend([
            "alias(",
            '    name = "target",',
            f'    actual = ":{_target(graph["target"])}",',
            '    visibility = ["PUBLIC"],',
            ")",
            "",
        ])
    return "\n".join(lines)
